import { Providers } from "@/components/providers";
import { Inter, Schibsted_Grotesk } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Navbar } from "@/components/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });
const schibsted_grotesk = Schibsted_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body className={schibsted_grotesk.className}>
       
        <Providers>
          <Toaster />
          <div>
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
